add support fo LoongArch64
loongarch64/gnu-efi pull request #1
Opened 2021-07-02 01:58 UTC by Xiao-Tao

Add the LoongArch64 architecture.

2021-07-04 12:21 UTC, yetist commented on apps/lfbgrid.c
> +    (defined (__riscv) && __riscv_xlen == 64) || defined(__loongarch64)
loongarch建议单列一行会不会好点？

2021-07-04 12:21 UTC, yetist commented on gnuefi/crt0-efi-loongarch64.S
> +	bl 	  	_relocate
从web上看这里对齐似乎有点问题？

2021-07-04 12:21 UTC, yetist commented on gnuefi/crt0-efi-loongarch64.S
> +	.align		4
4未对齐？

2021-07-04 12:21 UTC, yetist commented on gnuefi/reloc_loongarch64.c
> +   Copyright (C) 2021 Zhou mingtao <zhoumingtao@loongson.cn>
未遵循原有年份排列方式。

2021-07-04 12:21 UTC, yetist commented on gnuefi/reloc_loongarch64.c
> +/* reloc_loongarch64.c - position independent x86 ELF shared object relocator
描述有误，不是x86

2021-07-04 12:21 UTC, yetist commented on gnuefi/reloc_loongarch64.c
> +		      EFI_HANDLE image EFI_UNUSED,
EFI_HANDLE应对齐到long.

2021-07-04 12:21 UTC, yetist commented on gnuefi/crt0-efi-loongarch64.S
> +	.short	0x6264				// loongarch64 little endian
0x6264这个id是不是就最终下来了？

2021-07-04 12:24 UTC, yetist commented
@loongarch64/dev-team @zwaizwai 请review，谢谢。

2021-07-05 02:55 UTC, zhuyaliang commented on Make.defaults
> +  CFLAGS += -march=loongarch64
unrecognized argument in option ‘-march=loongarch64’

2021-07-05 03:03 UTC, kilaterlee commented on gnuefi/crt0-efi-loongarch64.S
> +	.short	0x6264				// loongarch64 little endian
先按这个ID走，确定后我通知你们

2021-07-05 08:29 UTC, cnmushiba commented on inc/efi.h
> +#elif defined (__loongarch64)
_M_XXX应该是微软的vs编译器和架构相关的宏定义，可以暂不处理。后面几个架构都是有序的，loongarch64加到mips64前面是不是比较好一点？

2021-07-05 08:32 UTC, cnmushiba commented on lib/loongarch64/setjmp.S
> +available
这块的注释整理一下吧

2021-07-05 08:39 UTC, cnmushiba commented
这个除了在UEFI shell下测试apps目录生成的各种efi文件。对libefi.a和libgnuefi.a的测试，还有其他的测试方法吗？

2021-07-05 09:06 UTC, cnmushiba commented on apps/AllocPages.c
> +#define MAX_ADDR (((9ULL << 60) | (0xC << 28)) -1)
根据整个文件的内容，似乎不用为loongarch64加MAX_ADDR?

2021-07-05 09:06 UTC, cnmushiba commented on apps/FreePages.c
> +#define MAX_ADDR (((9ULL << 60) | (0xC << 28)) -1)
根据整个文件的内容，似乎不用为loongarch64加MAX_ADDR?

2021-07-17 08:31 UTC, Xiao-Tao commented on inc/efi.h
> +#elif defined (__loongarch64)
这个按架构提交的先后顺序排序的，插队放在前面感觉不太合适：）

2021-12-16 06:34 UTC, cnmushiba approved these changes
大部分都确定下来了，感觉可以加速了推了

2021-12-16 07:06 UTC, xen0n requested changes

2021-12-16 07:06 UTC, xen0n commented on Make.defaults
> +  ARCH3264 = -mabi=lp64
老工具链写法，新的要写 `-mabi=lp64s`（如果默认不给用 FPU），`lp64` 过不了编译了。

2021-12-16 07:06 UTC, xen0n commented on apps/FreePages.c
> +#define MAX_ADDR (((9ULL << 60) | (0xC << 28)) -1)
这个问题原作者回复一下？

2021-12-16 07:06 UTC, xen0n commented on apps/lfbgrid.c
> +    (defined (__riscv) && __riscv_xlen == 64) || defined(__loongarch64)
为啥上面那个改动是换了一行，这里不换行？

2021-12-16 07:06 UTC, xen0n commented on gnuefi/crt0-efi-loongarch64.S
> + * crt0-efi-loongarch64.S - PE/COFF header for LOONGARCH64 EFI applications
```suggestion
 * crt0-efi-loongarch64.S - PE/COFF header for LoongArch64 EFI applications
```

别的这种全大写 LoongArch 也自行排查一下改掉

2021-12-16 07:06 UTC, xen0n commented on gnuefi/crt0-efi-loongarch64.S
> + * Copyright (C) 2021 Zhou mingtao <zhoumingtao@loongson.cn>
你名字不用首字母大写？

2021-12-16 07:06 UTC, xen0n commented on gnuefi/crt0-efi-loongarch64.S
> +	.short	0x6264				// loongarch64 little endian
这个现在倒是定下来了，看下别的架构是像这样写死还是定义了符号

2021-12-16 07:06 UTC, xen0n commented on gnuefi/crt0-efi-loongarch64.S
> +	.long	0xe0500020		// Characteristics (section flags)
这个别的架构也是写死 magic number 的吗？

2021-12-16 07:06 UTC, xen0n commented on gnuefi/crt0-efi-loongarch64.S
> +	jirl	  $ra, $ra, 0
为啥函数返回时候顺带写 `$ra`，这是过程调用写法，不是直接 `jr $ra` 就够了吗

2021-12-16 07:06 UTC, xen0n commented on inc/loongarch64/efibind.h
> +typedef signed char         int8_t;   // unqualified 'char' is unsigned on ARM
注释是直接从 ARM 抄来的，可以直接去掉（他们是解释了为啥不用裸的 `char` 类型，但 LA 编译器的 `char` 默认是有符号的，但明确写上 `signed` 其实是符合 C 标准的，因为 `char` 默认有没有符号是可以通过 CFLAGS 动态修改的）

2021-12-16 07:06 UTC, xen0n commented on lib/loongarch64/setjmp.S
> +	jirl $zero,$ra,0
现在有 `jr $ra` 写法可以用了，改掉吧，下同

2022-02-22 11:11 UTC, yetist commented
在最新物理地址固件上，gnu-efi 生成的 efi 会出问题，麻烦关注一下

2022-02-22 12:51 UTC, Xiao-Tao commented on lib/loongarch64/setjmp.S
> +available
已清理

2022-02-22 12:53 UTC, Xiao-Tao commented on apps/FreePages.c
> +#define MAX_ADDR (((9ULL << 60) | (0xC << 28)) -1)
Orz，忘记清理了，目前已清理

2022-02-22 12:54 UTC, Xiao-Tao commented on Make.defaults
> +  ARCH3264 = -mabi=lp64
已根据新工具链的用法，修改成lp64s

2022-02-22 12:54 UTC, Xiao-Tao commented on apps/lfbgrid.c
> +    (defined (__riscv) && __riscv_xlen == 64) || defined(__loongarch64)
已修改

2022-02-22 12:56 UTC, Xiao-Tao commented on gnuefi/crt0-efi-loongarch64.S
> + * Copyright (C) 2021 Zhou mingtao <zhoumingtao@loongson.cn>
已修改，感谢提醒

2022-02-22 12:56 UTC, Xiao-Tao commented on gnuefi/crt0-efi-loongarch64.S
> +	.long	0xe0500020		// Characteristics (section flags)
这个其他架构也是直接写死，没有定义符号

2022-02-22 12:57 UTC, Xiao-Tao commented on lib/loongarch64/setjmp.S
> +	jirl $zero,$ra,0
已修改

2022-03-10 10:13 UTC, xry111 commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
这里我们需要用 libgcc 里面的函数吗？

如果不需要，我们也和 arm 一样把这个去掉。我本地测试编译出的 `*.so` 是没有 UND 符号的，所以似乎把这里去掉就行了。

2022-03-10 10:14 UTC, xry111 commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
如果去不掉这个那就真的没有办法，确实需要 LP64S 版本的 libgcc.a 了……

2022-03-10 10:25 UTC, xry111 commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
或者给 LDFLAGS 加上 --as-needed 也行，这样如果没有用到 libgcc 的函数就能正常链接，否则会报错。

从 https://github.com/archlinux/svntogit-packages/blob/packages/gnu-efi/trunk/gnu-efi-3.0.12-ldflags.patch 学来的。

2022-03-10 11:19 UTC, scylaac commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
上游是不是有可能把 `-ffreestanding` 和 `-nostdlib` 的意思搞混了？

2022-03-10 11:22 UTC, xry111 commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
> 上游是不是有可能把 `-ffreestanding` 和 `-nostdlib` 的意思搞混了？

它是在链接的时候用了 `-nostdlib`，但是这个地方它对于除了 ARM 以外的所有东西都显式加了个 libgcc ...

具体为啥我也不知道。

2022-03-10 11:23 UTC, scylaac commented on Make.defaults
> +  ARCH3264 = -mabi=lp64s
我试了一下，对于默认 `lp64d` 的工具链，用 `-mabi=lp64s -nostdlib` 会少打印很多提示信息。但感觉 `-nostdlib` 也许应该放到公共的 `CFLAGS` 里面？

2022-03-10 11:25 UTC, scylaac commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
那个 `LDFLAGS` 里面的 `-nostdlib` 好像是直接给 ld 的吧，gcc 也需要。

2022-03-11 02:58 UTC, yetist commented
请 rebase 到最新代码上，并检查 `inc/efiapi.h` 文件是否漏加 `EFI_IMAGE_MACHINE_LOONGARCH64` 定义

2022-03-11 04:49 UTC, yetist commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
链接 gcc 是需要的，见这里的公共代码：
https://github.com/systemd/systemd/blob/0d3c36641d071bc0370237245aecab1380a4f189/src/boot/efi/meson.build#L409

2022-03-11 05:07 UTC, xry111 commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
可以试试去掉它行不行，不行的话就确实需要 LP64S 的 libgcc 了。

作为发行版维护的角度来说可以在构建 GCC 时开着 multilib，然后拆包 (把 libgcc:loongarch64-linux-gnuabisf 单独放一个包里面)，然后 systemd-boot 在构建时依赖 libgcc:loongarch64-linux-gnuabisf。但是我作为 LFS editor 极其讨厌“交叉编译时链接系统库”这种做法。

2022-03-11 06:16 UTC, yetist commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
改这里没啥作用，关键还是在上面的 `-mabi=lp64s` 部分。建议直接去掉对 ARCH3264 变量的定义，从名字来看，这个变量只是用来设置-m32或-m64的。

2022-03-14 09:58 UTC, scylaac commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
@yetist 我们的 gnu-efi 计划支持硬浮点程序吗？我看到 riscv64 的 setjmp.S 有保存浮点寄存器的功能，支持 `s`  和 `d` 两种 ABI，但 loongarch64 这边还没有。

2022-03-15 01:41 UTC, yetist commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
@scylaac  难道说在固件中是可以使用浮点寄存器的吗？我之前了解是没使用浮点啊，但是看aarch64、mips64el和riscv64 貌似都保存恢复了浮点寄存器，有点奇怪。

2022-03-15 02:33 UTC, xen0n commented on Make.defaults
>  export LIBGCC=$(shell $(CC) $(ARCH3264) -print-libgcc-file-name)
正常肯定不该用，因为不用也不会怎么样，并且有浮点上下文归谁的问题（如果涉及内核回调之类神奇的场景），所以尽量是不要用

至于一定要用的话，因为这些架构的 FPU 都不需要特殊初始化就能用了，所以可能在确定 FPU 存在的前提下进行一下保存恢复会比较安全（ABI 而言）吧。我猜的 :-)

2022-03-23 15:54 UTC, xen0n commented on Make.defaults
> +  ARCH3264 = -mabi=lp64s
因为固件环境肯定没得正常的 C 库用，`-nostdlib` 我觉得合理

2022-03-23 17:19 UTC, xry111 commented on Make.defaults
> +  ARCH3264 = -mabi=lp64s
我估计上游会问你 “`-nostdlib` 不是只影响链接时的行为嘛”。因为 GCC 的 man page 里面*暗示*了这个东西不会影响编译时的行为：

```
           The compiler may generate calls to "memcmp", "memset", "memcpy" and
           "memmove".  These entries are usually resolved by entries in libc.
           These entry points should be supplied through some other mechanism
           when this option is specified.
```

就是说就算你指定了 `-nostdlib` ，编译阶段还是会不管你有没有 lib 然后去生成这些。

2022-03-25 15:42 UTC, xen0n commented
原作者不活跃了？我帮着 rebase 了一下，提交没整理（预期是等全部 review 完之后再整理）

@yetist: 确认下这个版本的 gnu-efi 在新老固件都能用吗？如果不能用的话大概哪个地方坏了？我必须有可以工作的 gnu-efi 才能尝试制作新老固件的兼容层。

2022-06-27 07:18 UTC, xen0n commented
Ping?

2022-07-07 03:32 UTC, yetist commented on Make.defaults
> +  ARCH3264 = -mabi=lp64s
建议去掉 lp64s，否则链接出错。

2022-11-16 08:01 UTC, xen0n commented
Ping again

This is blocking things like `fwupd-efi` or `systemd-boot` for example

2022-12-21 04:55 UTC, xen0n commented
This is [already upstream](https://sourceforge.net/p/gnu-efi/code/merge-requests/29/), congrats!

2022-12-21 04:55 UTC, closed without merging

2022-12-21 09:01 UTC, yetist commented
进去了？不错不错，验证一下，不知道合并的那个补丁，有没有及时更新。

2022-12-21 09:02 UTC, yetist commented
gnu-efi 和 libseccomp 估计是 loongarch 上合并时间最久的两个补丁了，都需要一年时间...

2022-12-21 09:03 UTC, yetist commented
gnu-efi 和 libseccomp 估计是 loongarch 上合并时间最久的两个补丁了，都需要一年时间...